// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentService.proto

package com.song.cn.agent.grpc;

public final class MyDataInfo {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_song_cn_grpc_MyRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_song_cn_grpc_MyRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_song_cn_grpc_MyResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_song_cn_grpc_MyResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\024StudentService.proto\022\020com.song.cn.grpc" +
                        "\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRes" +
                        "ponse\022\020\n\010realName\030\002 \001(\t2f\n\016StudentServic" +
                        "e\022T\n\025GetRealNameByUsername\022\033.com.song.cn" +
                        ".grpc.MyRequest\032\034.com.song.cn.grpc.MyRes" +
                        "ponse\"\000B \n\020com.song.cn.grpcB\nMyDataInfoP" +
                        "\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_com_song_cn_grpc_MyRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_song_cn_grpc_MyRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_song_cn_grpc_MyRequest_descriptor,
                new String[]{"Username",});
        internal_static_com_song_cn_grpc_MyResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_song_cn_grpc_MyResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_song_cn_grpc_MyResponse_descriptor,
                new String[]{"RealName",});
    }

    private MyDataInfo() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
