// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentService.proto

package com.song.cn.agent.grpc;

public interface MyResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.song.cn.grpc.MyResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string realName = 2;</code>
     */
    String getRealName();

    /**
     * <code>string realName = 2;</code>
     */
    com.google.protobuf.ByteString
    getRealNameBytes();
}
